import { Link, useNavigate } from 'react-router-dom';
import { ArrowRight, Eye, EyeOff, Mail, LockKeyhole } from 'lucide-react';
import { useState } from 'react';
import { useAuth } from '../../state/AuthContext';
import { useAuthForm } from '../../hooks/useAuthForm';
import { usePasswordStrength } from '../../hooks/usePasswordStrength';
import { Button } from '../../../../shared/components/Button/Button';
import { Input } from '../../../../shared/components/Input/Input';
import { Alert } from '../../../../shared/components/Alert/Alert';
import { PasswordStrength } from '../PasswordStrength/PasswordStrength';
import styles from './RegisterForm.module.scss';

export function RegisterForm(){const {register,loading}=useAuth();const nav=useNavigate();const {form,errors,serverError,setServerError,update,validate}=useAuthForm('register');const strength=usePasswordStrength(form.password);const [show,setShow]=useState(false);const submit=async e=>{e.preventDefault();if(!validate())return;const r=await register({email:form.email.trim(),password:form.password});if(r.success)nav('/login',{replace:true,state:{registered:true}});else setServerError(r.error?.message || r.message || "Unable to create your account.")};return <section className={styles.card}><div className={styles.topline}><span className={styles.dot}/>NEXEDGE</div><div className={styles.kicker}><span/>GET STARTED</div><h1>Create account<span>.</span></h1><p className={styles.subtitle}>Set up your secure NexEdge account in a few simple steps.</p>{serverError&&<Alert type="error">{serverError}</Alert>}<form onSubmit={submit} noValidate><Input label="Email address" name="email" value={form.email} onChange={update} placeholder="you@example.com" autoComplete="email" error={errors.email} icon={<Mail size={18}/>} /><Input label="Password" name="password" type={show?'text':'password'} value={form.password} onChange={update} placeholder="Create a password" autoComplete="new-password" error={errors.password} icon={<LockKeyhole size={18}/>} endAdornment={<button type="button" className={styles.eye} onClick={()=>setShow(v=>!v)} aria-label={show?'Hide password':'Show password'}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button>}/><PasswordStrength {...strength}/><Input label="Confirm password" name="confirmPassword" type={show?'text':'password'} value={form.confirmPassword} onChange={update} placeholder="Repeat your password" autoComplete="new-password" error={errors.confirmPassword}/><label className={styles.terms}><input type="checkbox" name="terms" checked={form.terms} onChange={update}/><span>I agree to the terms and understand that my account is protected.</span></label>{errors.terms&&<div className={styles.termError}>{errors.terms}</div>}<Button type="submit" loading={loading}>Create account <ArrowRight size={18}/></Button></form><p className={styles.switch}>Already have an account? <Link to="/login">Sign in</Link></p></section>}
